/**
 * IndexNow integration — pings Bing + Yandex (+ now several other engines)
 * with a URL list so they crawl + index new pages in seconds instead of
 * waiting weeks for the next organic crawl cycle.
 *
 * Spec: https://www.indexnow.org/documentation
 *
 * Setup:
 *  1. A static key file lives at /{INDEXNOW_KEY}.txt and contains the key
 *     as plaintext. (public/56e3c023da9842dea1928b02ff82dd9b.txt)
 *  2. POST our URL list to https://api.indexnow.org/indexnow with body
 *     `{ host, key, keyLocation, urlList }`.
 *  3. IndexNow shares the submission with all participating search engines
 *     (Bing, Yandex, Naver, Seznam, Yep, plus Google reading the ledger
 *     for indexing hints).
 *
 * No env var needed — the key is public by design (whoever owns the file
 * at the key URL is the trusted owner). Rotating just means picking a new
 * key + uploading the new key file.
 */

const HOST = "nohomailbox.org";
const KEY = "56e3c023da9842dea1928b02ff82dd9b";
const KEY_LOCATION = `https://${HOST}/${KEY}.txt`;
const ENDPOINT = "https://api.indexnow.org/indexnow";
// IndexNow caps batches at 10,000 URLs per POST. We don't approach that
// but chunk defensively so a future programmatic-SEO explosion doesn't
// silently hit the wall.
const BATCH_LIMIT = 9_000;

export type IndexNowResult = {
  ok: boolean;
  status: number;
  submitted: number;
  error?: string;
};

/**
 * Push a list of URLs to IndexNow. URLs must be full https://nohomailbox.org/...
 * URLs (no relative paths). Returns one result per HTTP batch.
 */
export async function pingIndexNow(urls: string[]): Promise<IndexNowResult[]> {
  if (urls.length === 0) return [];

  // De-dupe + only accept URLs on our host (IndexNow rejects cross-host
  // submissions and our key file only signs our own domain anyway).
  const valid = Array.from(new Set(urls)).filter(
    (u) => u.startsWith(`https://${HOST}/`) || u === `https://${HOST}`,
  );
  if (valid.length === 0) return [];

  const batches: string[][] = [];
  for (let i = 0; i < valid.length; i += BATCH_LIMIT) {
    batches.push(valid.slice(i, i + BATCH_LIMIT));
  }

  const results: IndexNowResult[] = [];
  for (const batch of batches) {
    try {
      const res = await fetch(ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json; charset=utf-8" },
        body: JSON.stringify({
          host: HOST,
          key: KEY,
          keyLocation: KEY_LOCATION,
          urlList: batch,
        }),
      });
      results.push({
        ok: res.ok,
        status: res.status,
        submitted: batch.length,
        // 200 OK = submitted, 202 = accepted, 422 = URL host mismatch,
        // 403 = key file mismatch, 429 = rate-limited. Don't throw on
        // non-200 — caller decides whether to retry.
        error: res.ok ? undefined : `HTTP ${res.status}`,
      });
    } catch (e) {
      results.push({
        ok: false,
        status: 0,
        submitted: 0,
        error: e instanceof Error ? e.message : String(e),
      });
    }
  }
  return results;
}

/**
 * Convenience: pull every URL from the live sitemap and push the whole
 * lot. Use sparingly — once per major content batch or daily cron, not
 * per page load. Returns a summary.
 */
export async function pingSitemap(): Promise<{
  total: number;
  succeeded: number;
  failed: number;
  batches: IndexNowResult[];
}> {
  // Read sitemap directly from the deployed origin so we don't have to
  // re-implement the URL set here.
  const res = await fetch(`https://${HOST}/sitemap.xml`, { cache: "no-store" });
  if (!res.ok) {
    return {
      total: 0,
      succeeded: 0,
      failed: 1,
      batches: [{ ok: false, status: res.status, submitted: 0, error: "sitemap fetch failed" }],
    };
  }
  const xml = await res.text();
  // Extract every <loc>…</loc>. Cheap regex parse — sitemap.xml is always
  // machine-generated by next, no edge-cases.
  const urls = Array.from(xml.matchAll(/<loc>([^<]+)<\/loc>/g)).map((m) => m[1]!);

  const batches = await pingIndexNow(urls);
  return {
    total: urls.length,
    succeeded: batches.filter((b) => b.ok).reduce((a, b) => a + b.submitted, 0),
    failed: batches.filter((b) => !b.ok).length,
    batches,
  };
}
