// State-by-state LLC formation landing pages. Top US states by LLC formation
// volume. Each page targets buying-intent queries like "[state] LLC formation"
// or "how to form an LLC in [state]" and pitches our $2k Business Launch
// Bundle as the all-in alternative to piecemeal LegalZoom services.

export type StateLLC = {
  slug: string;
  name: string;
  abbr: string;
  filingFee: number;
  filingForm: string;
  franchiseTax: { amount: number; cadence: string; note: string } | null;
  annualReport: { fee: number; cadence: string } | null;
  registeredAgent: string;
  paStateUrl: string; // SOS business search
  highlights: string[];
  watchOuts: string[];
  estTotalYear1: { low: number; high: number };
  realAddressNote: string;
};

export const STATE_LLC_PAGES: StateLLC[] = [
  {
    slug: "california",
    name: "California",
    abbr: "CA",
    filingFee: 70,
    filingForm: "LLC-1 (Articles of Organization)",
    franchiseTax: {
      amount: 800,
      cadence: "annual",
      note: "Even if revenue is $0. Plus possible income-based fee on revenue over $250k.",
    },
    annualReport: { fee: 20, cadence: "every 2 years" },
    registeredAgent:
      "Required. Must have a real California physical address (P.O. Boxes rejected).",
    paStateUrl: "https://bizfileonline.sos.ca.gov/search/business",
    highlights: [
      "Largest US economy if it were a country",
      "Strong liability protections",
      "Robust trademark and IP environment",
    ],
    watchOuts: [
      "$800/year franchise tax even with $0 revenue",
      "Income-based fee starts at $250k revenue",
      "P.O. Box not allowed for state filing or DRE/CSLB licenses",
    ],
    estTotalYear1: { low: 890, high: 1400 },
    realAddressNote:
      "Must be a real California street address. Our Lankershim Blvd address works for the filing — most CA-based filers use a CMRA address like ours.",
  },
  {
    slug: "texas",
    name: "Texas",
    abbr: "TX",
    filingFee: 300,
    filingForm: "Form 205 (Certificate of Formation)",
    franchiseTax: {
      amount: 0,
      cadence: "annual (no-tax-due if revenue under $2.47M)",
      note: "No franchise tax under threshold. Above $2.47M revenue, tax applies (varies).",
    },
    annualReport: { fee: 0, cadence: "annual public information report" },
    registeredAgent:
      "Required. Must have a Texas physical address. Can be the LLC owner if they have a TX address.",
    paStateUrl: "https://mycpa.cpa.state.tx.us/coa/",
    highlights: [
      "No state income tax",
      "No franchise tax under $2.47M revenue",
      "Strong asset-protection state",
    ],
    watchOuts: [
      "$300 filing fee is one of the highest in the US",
      "Texas SOS sometimes runs slow (4–6 weeks online filing)",
    ],
    estTotalYear1: { low: 320, high: 600 },
    realAddressNote:
      "If you don&apos;t have a Texas address, you&apos;ll need a Texas registered agent service ($50–$300/yr). We can pair you with one as part of our bundle.",
  },
  {
    slug: "florida",
    name: "Florida",
    abbr: "FL",
    filingFee: 125,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 138.75, cadence: "annual" },
    registeredAgent:
      "Required. Must have a Florida physical address.",
    paStateUrl: "https://search.sunbiz.org/Inquiry/CorporationSearch/ByName",
    highlights: [
      "No state income tax",
      "No franchise tax",
      "Fast online filing (1–2 days)",
      "Friendly small-business climate",
    ],
    watchOuts: [
      "Annual report deadline is May 1 — late fee is $400",
      "Common filing rejection: business name too similar to existing entity",
    ],
    estTotalYear1: { low: 264, high: 500 },
    realAddressNote:
      "Need a Florida physical address for the registered agent. Standard registered-agent services run $50–$300/yr.",
  },
  {
    slug: "new-york",
    name: "New York",
    abbr: "NY",
    filingFee: 200,
    filingForm: "Articles of Organization (DOS-1336)",
    franchiseTax: {
      amount: 25,
      cadence: "annual minimum",
      note: "$25 minimum, scales with revenue. Higher than most states for active LLCs.",
    },
    annualReport: { fee: 9, cadence: "every 2 years (biennial statement)" },
    registeredAgent:
      "The NY Secretary of State serves as default registered agent. Optional commercial agent.",
    paStateUrl: "https://apps.dos.ny.gov/publicInquiry/",
    highlights: [
      "Default registered agent (the SOS) means no agent fee required",
      "Strong trademark protection (NY courts)",
    ],
    watchOuts: [
      "Publication requirement: must publish notice in 2 newspapers in your county for 6 weeks. Costs $50–$2,000 depending on county (NYC counties are the worst).",
      "Failing publication = LLC suspended",
    ],
    estTotalYear1: { low: 360, high: 2300 },
    realAddressNote:
      "NY publication requirement is the biggest gotcha — can hit $2k in Manhattan. Plan for it.",
  },
  {
    slug: "illinois",
    name: "Illinois",
    abbr: "IL",
    filingFee: 150,
    filingForm: "Articles of Organization (LLC-5.5)",
    franchiseTax: null,
    annualReport: { fee: 75, cadence: "annual" },
    registeredAgent: "Required. Must have an Illinois physical address.",
    paStateUrl: "https://www.ilsos.gov/corporatellc/",
    highlights: [
      "No franchise tax",
      "Reasonable filing + annual fees",
    ],
    watchOuts: [
      "Annual report due before the first day of the LLC&apos;s anniversary month",
      "Late fee + reinstatement can hit $300+",
    ],
    estTotalYear1: { low: 225, high: 450 },
    realAddressNote:
      "Illinois requires a real Illinois physical address for the registered agent. Standard service runs $50–$300/yr.",
  },
  {
    slug: "georgia",
    name: "Georgia",
    abbr: "GA",
    filingFee: 100,
    filingForm: "Articles of Organization (CD-030)",
    franchiseTax: null,
    annualReport: { fee: 50, cadence: "annual" },
    registeredAgent: "Required. Must have a Georgia physical address.",
    paStateUrl: "https://ecorp.sos.ga.gov/BusinessSearch",
    highlights: [
      "Low filing fees",
      "No franchise tax",
      "Atlanta startup ecosystem",
    ],
    watchOuts: [
      "Annual registration fee due April 1 each year",
      "Foreign LLC requires additional registration if doing business in GA but formed elsewhere",
    ],
    estTotalYear1: { low: 150, high: 350 },
    realAddressNote:
      "Need a Georgia physical address for the registered agent.",
  },
  {
    slug: "north-carolina",
    name: "North Carolina",
    abbr: "NC",
    filingFee: 125,
    filingForm: "Articles of Organization (L-01)",
    franchiseTax: null,
    annualReport: { fee: 200, cadence: "annual" },
    registeredAgent:
      "Required. Must have a North Carolina physical address.",
    paStateUrl: "https://www.sosnc.gov/online_services/search/by_title/_business_registration",
    highlights: [
      "No franchise tax for LLCs",
      "Growing tech corridor (Research Triangle)",
    ],
    watchOuts: [
      "Annual report fee is $200 — one of the higher annual costs",
      "Articles must list all members (loss of privacy)",
    ],
    estTotalYear1: { low: 325, high: 600 },
    realAddressNote:
      "NC requires real physical address for registered agent.",
  },
  {
    slug: "ohio",
    name: "Ohio",
    abbr: "OH",
    filingFee: 99,
    filingForm: "Articles of Organization (533A)",
    franchiseTax: null,
    annualReport: null,
    registeredAgent:
      "Statutory agent required. Must have an Ohio physical address.",
    paStateUrl: "https://businesssearch.ohiosos.gov/",
    highlights: [
      "No annual report",
      "No franchise tax",
      "Lowest filing fee among top-10 states",
    ],
    watchOuts: [
      "Most affordable but legal protections aren&apos;t as strong as DE / NV",
      "Statutory agent must be Ohio-based",
    ],
    estTotalYear1: { low: 99, high: 250 },
    realAddressNote: "Need an Ohio physical address for the statutory agent.",
  },
  {
    slug: "pennsylvania",
    name: "Pennsylvania",
    abbr: "PA",
    filingFee: 125,
    filingForm: "Certificate of Organization (DSCB:15-8821)",
    franchiseTax: null,
    annualReport: { fee: 7, cadence: "decennial (every 10 years)" },
    registeredAgent:
      "Required commercial registered office. Must be a PA physical address.",
    paStateUrl:
      "https://www.corporations.pa.gov/search/corpsearch",
    highlights: [
      "Decennial report (every 10 years) means low ongoing admin",
      "No franchise tax",
    ],
    watchOuts: [
      "Newspaper publication requirement in some counties",
      "Failing publication can void the LLC",
    ],
    estTotalYear1: { low: 200, high: 600 },
    realAddressNote:
      "PA requires a registered office (commercial address) in PA — not just a registered agent.",
  },
  {
    slug: "new-jersey",
    name: "New Jersey",
    abbr: "NJ",
    filingFee: 125,
    filingForm: "Public Records Filing (LLC-1)",
    franchiseTax: null,
    annualReport: { fee: 75, cadence: "annual" },
    registeredAgent: "Required. Must have a New Jersey physical address.",
    paStateUrl:
      "https://www.njportal.com/DOR/businessrecords/EntityDocs/BusinessStatusReport",
    highlights: [
      "No franchise tax for LLCs",
      "Close to NYC market",
    ],
    watchOuts: [
      "$75/yr annual report",
      "Foreign LLCs doing business in NJ require separate registration",
    ],
    estTotalYear1: { low: 200, high: 500 },
    realAddressNote: "NJ requires a real NJ address for the registered agent.",
  },
  {
    slug: "washington",
    name: "Washington",
    abbr: "WA",
    filingFee: 200,
    filingForm: "Certificate of Formation",
    franchiseTax: null,
    annualReport: { fee: 70, cadence: "annual (initial), then $60" },
    registeredAgent: "Required. Must have a Washington physical address.",
    paStateUrl: "https://ccfs.sos.wa.gov/#/",
    highlights: [
      "No state income tax (great for owners)",
      "No franchise tax",
      "Strong tech ecosystem in Seattle",
    ],
    watchOuts: [
      "B&O (Business and Occupation) tax — gross-receipts tax, ~0.5% of gross",
      "First annual report due within 120 days of formation, then yearly",
    ],
    estTotalYear1: { low: 270, high: 600 },
    realAddressNote:
      "WA requires a real Washington address. Common pitfall: B&O tax — keep accurate revenue records from day 1.",
  },
  {
    slug: "massachusetts",
    name: "Massachusetts",
    abbr: "MA",
    filingFee: 500,
    filingForm: "Certificate of Organization",
    franchiseTax: null,
    annualReport: { fee: 500, cadence: "annual" },
    registeredAgent: "Required. Must have a Massachusetts physical address.",
    paStateUrl: "https://corp.sec.state.ma.us/CorpWeb/CorpSearch/CorpSearch.aspx",
    highlights: [
      "Strong legal protections",
      "Boston / Cambridge tech and biotech ecosystems",
    ],
    watchOuts: [
      "$500 filing fee — highest among top-15 states",
      "$500 annual report fee — same",
      "MA business taxation can get complex — talk to a CPA",
    ],
    estTotalYear1: { low: 1000, high: 1500 },
    realAddressNote:
      "MA requires a real Massachusetts address for the registered agent.",
  },
  {
    slug: "virginia",
    name: "Virginia",
    abbr: "VA",
    filingFee: 100,
    filingForm: "Articles of Organization (LLC-1011)",
    franchiseTax: null,
    annualReport: { fee: 50, cadence: "annual" },
    registeredAgent: "Required. Must have a Virginia physical address.",
    paStateUrl: "https://cis.scc.virginia.gov/EntitySearch/Index",
    highlights: [
      "Low filing fee",
      "No franchise tax",
      "Government and defense contracting hub (DC metro)",
    ],
    watchOuts: [
      "Annual report deadline = last day of LLC&apos;s anniversary month",
      "Foreign LLCs need to register separately if doing business in VA",
    ],
    estTotalYear1: { low: 150, high: 400 },
    realAddressNote: "VA requires a real Virginia address.",
  },
  {
    slug: "michigan",
    name: "Michigan",
    abbr: "MI",
    filingFee: 50,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 25, cadence: "annual" },
    registeredAgent: "Required. Must have a Michigan physical address.",
    paStateUrl: "https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSearch.aspx",
    highlights: [
      "Lowest filing fee among top-15 states ($50)",
      "Lowest annual report fee ($25)",
      "Detroit / Ann Arbor manufacturing + tech",
    ],
    watchOuts: [
      "Annual report due by Feb 15 each year",
      "Late filing $25 penalty",
    ],
    estTotalYear1: { low: 75, high: 250 },
    realAddressNote: "MI requires a real Michigan address.",
  },
  {
    slug: "arizona",
    name: "Arizona",
    abbr: "AZ",
    filingFee: 50,
    filingForm: "Articles of Organization (L010)",
    franchiseTax: null,
    annualReport: null,
    registeredAgent: "Required. Statutory agent must have Arizona physical address.",
    paStateUrl: "https://ecorp.azcc.gov/EntitySearch/Index",
    highlights: [
      "$50 filing fee — among the lowest",
      "No annual report",
      "No franchise tax",
      "Booming Phoenix tech and small-business climate",
    ],
    watchOuts: [
      "Publication requirement in some counties (must publish notice in newspaper)",
      "Maricopa and Pima counties exempt from publication, but most others aren&apos;t",
    ],
    estTotalYear1: { low: 50, high: 350 },
    realAddressNote:
      "AZ requires a real Arizona address. Publication can add $50–$300 in non-exempt counties.",
  },
  {
    slug: "nevada",
    name: "Nevada",
    abbr: "NV",
    filingFee: 425,
    filingForm: "Articles of Organization + Initial List + Business License",
    franchiseTax: null,
    annualReport: { fee: 350, cadence: "annual (List + Business License)" },
    registeredAgent: "Required. Must have a Nevada physical address.",
    paStateUrl: "https://www.nvsilverflume.gov/businessSearch",
    highlights: [
      "No state income tax",
      "Strong privacy laws",
      "Charging order protection",
      "Popular for asset protection",
    ],
    watchOuts: [
      "$425 first-year cost is among the highest (filing + initial list + business license)",
      "$350/yr ongoing fees",
      "Foreign-LLC traps — many Nevada LLCs are technically doing business in CA/TX and pay double",
    ],
    estTotalYear1: { low: 425, high: 800 },
    realAddressNote:
      "NV is famous for LLC arbitrage but unless you actually live in Nevada, your home state will likely require foreign-LLC registration AND state taxes. Talk to a CPA before forming in NV when you live elsewhere.",
  },
  {
    slug: "oregon",
    name: "Oregon",
    abbr: "OR",
    filingFee: 100,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 100, cadence: "annual" },
    registeredAgent: "Required. Must have an Oregon physical address.",
    paStateUrl: "https://sos.oregon.gov/business/Pages/find.aspx",
    highlights: [
      "No sales tax (great for e-com sellers)",
      "Portland tech ecosystem",
      "Reasonable filing fees",
    ],
    watchOuts: [
      "Annual report due on anniversary date — easy to miss",
      "Failure to file = administrative dissolution",
    ],
    estTotalYear1: { low: 200, high: 500 },
    realAddressNote: "OR requires a real Oregon physical address for the registered agent.",
  },
  {
    slug: "colorado",
    name: "Colorado",
    abbr: "CO",
    filingFee: 50,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 25, cadence: "annual periodic report" },
    registeredAgent: "Required. Must have a Colorado physical address.",
    paStateUrl: "https://www.coloradosos.gov/biz/BusinessEntityCriteriaExt.do",
    highlights: [
      "$50 filing fee — among the cheapest",
      "$25/yr periodic report",
      "Strong Denver/Boulder tech and outdoor-industry ecosystem",
    ],
    watchOuts: [
      "Periodic report due in the LLC&apos;s anniversary month, +2 months grace",
      "Forms entirely online (no paper filing)",
    ],
    estTotalYear1: { low: 75, high: 300 },
    realAddressNote: "CO requires a real Colorado physical address.",
  },
  {
    slug: "tennessee",
    name: "Tennessee",
    abbr: "TN",
    filingFee: 300,
    filingForm: "Articles of Organization",
    franchiseTax: {
      amount: 100,
      cadence: "annual minimum",
      note: "Franchise + excise tax based on net worth or income, $100 minimum.",
    },
    annualReport: { fee: 300, cadence: "annual" },
    registeredAgent: "Required. Must have a Tennessee physical address.",
    paStateUrl: "https://tnbear.tn.gov/Ecommerce/FilingSearch.aspx",
    highlights: [
      "No state income tax",
      "Nashville business-friendly climate",
      "Strong music + healthcare industries",
    ],
    watchOuts: [
      "$300 filing fee (above average)",
      "$300 annual report (also above average)",
      "Franchise + excise tax applies even on small businesses",
    ],
    estTotalYear1: { low: 700, high: 1100 },
    realAddressNote: "TN requires a real Tennessee physical address.",
  },
  {
    slug: "minnesota",
    name: "Minnesota",
    abbr: "MN",
    filingFee: 155,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 0, cadence: "annual renewal (free if on time)" },
    registeredAgent: "Required. Must have a Minnesota physical address.",
    paStateUrl: "https://mblsportal.sos.state.mn.us/Business/Search",
    highlights: [
      "Free annual renewal (if filed on time)",
      "No franchise tax",
      "Twin Cities Fortune 500 ecosystem",
    ],
    watchOuts: [
      "Annual renewal late fee is $25 + you risk dissolution",
      "Renewal MUST be filed (not just paid) by Dec 31 each year",
    ],
    estTotalYear1: { low: 155, high: 400 },
    realAddressNote: "MN requires a real Minnesota physical address.",
  },
  {
    slug: "wisconsin",
    name: "Wisconsin",
    abbr: "WI",
    filingFee: 130,
    filingForm: "Articles of Organization (online)",
    franchiseTax: null,
    annualReport: { fee: 25, cadence: "annual" },
    registeredAgent: "Required. Must have a Wisconsin physical address.",
    paStateUrl: "https://www.wdfi.org/apps/CorpSearch/Search.aspx",
    highlights: [
      "$130 online filing (lower than paper $170)",
      "$25 annual report — among the cheapest in the US",
      "No franchise tax for LLCs",
    ],
    watchOuts: [
      "Annual report due by end of registration anniversary quarter",
      "Late = $25 fee + administrative dissolution risk",
    ],
    estTotalYear1: { low: 155, high: 400 },
    realAddressNote: "WI requires a real Wisconsin physical address.",
  },
  {
    slug: "maryland",
    name: "Maryland",
    abbr: "MD",
    filingFee: 100,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 300, cadence: "annual" },
    registeredAgent: "Required. Must have a Maryland physical address.",
    paStateUrl: "https://egov.maryland.gov/BusinessExpress/EntitySearch",
    highlights: [
      "Proximity to DC / federal contracting market",
      "Strong biotech + cybersecurity ecosystems",
      "Personal property tax now waived for most small LLCs",
    ],
    watchOuts: [
      "$300/year annual report fee (high)",
      "Personal property return required even if exempt",
    ],
    estTotalYear1: { low: 400, high: 700 },
    realAddressNote: "MD requires a real Maryland physical address.",
  },
  {
    slug: "missouri",
    name: "Missouri",
    abbr: "MO",
    filingFee: 50,
    filingForm: "Articles of Organization (online)",
    franchiseTax: null,
    annualReport: null,
    registeredAgent: "Required. Must have a Missouri physical address.",
    paStateUrl: "https://bsd.sos.mo.gov/BusinessEntity/BESearch.aspx",
    highlights: [
      "$50 online filing — among the cheapest in the US",
      "No annual report",
      "No franchise tax",
    ],
    watchOuts: [
      "Paper filing is $105 — only file online",
      "Operating agreement is technically required (most owners skip it — we don't recommend that)",
    ],
    estTotalYear1: { low: 50, high: 200 },
    realAddressNote: "MO requires a real Missouri physical address.",
  },
  {
    slug: "indiana",
    name: "Indiana",
    abbr: "IN",
    filingFee: 95,
    filingForm: "Articles of Organization (online)",
    franchiseTax: null,
    annualReport: { fee: 32, cadence: "every 2 years" },
    registeredAgent: "Required. Must have an Indiana physical address.",
    paStateUrl: "https://bsd.sos.in.gov/PublicBusinessSearch",
    highlights: [
      "$32 biennial business entity report (very low)",
      "No franchise tax",
      "Strong manufacturing + logistics economy",
    ],
    watchOuts: [
      "Filing every 2 years — easy to miss the cycle",
      "Indiana Department of Revenue nexus is aggressive",
    ],
    estTotalYear1: { low: 95, high: 300 },
    realAddressNote: "IN requires a real Indiana physical address.",
  },
  {
    slug: "connecticut",
    name: "Connecticut",
    abbr: "CT",
    filingFee: 120,
    filingForm: "Certificate of Organization",
    franchiseTax: {
      amount: 250,
      cadence: "biennial",
      note: "Business Entity Tax (BET) every 2 years.",
    },
    annualReport: { fee: 80, cadence: "annual" },
    registeredAgent: "Required. Must have a Connecticut physical address.",
    paStateUrl: "https://service.ct.gov/business/s/onlinebusinesssearch",
    highlights: [
      "Wealthy customer base (Fairfield County)",
      "Proximity to NYC market",
      "Strong insurance and financial services hub",
    ],
    watchOuts: [
      "$80 annual report + $250 biennial BET = $410 / 2 yrs",
      "High overall regulatory burden",
    ],
    estTotalYear1: { low: 200, high: 600 },
    realAddressNote: "CT requires a real Connecticut physical address.",
  },
  {
    slug: "south-carolina",
    name: "South Carolina",
    abbr: "SC",
    filingFee: 110,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: null,
    registeredAgent: "Required. Must have a South Carolina physical address.",
    paStateUrl: "https://businessfilings.sc.gov/BusinessFiling/Entity/Search",
    highlights: [
      "No annual report for most LLCs",
      "No franchise tax",
      "Charleston / Greenville startup-friendly cities",
    ],
    watchOuts: [
      "If LLC elects S-corp tax: must file CL-1 + annual report",
      "License/permit costs vary by municipality",
    ],
    estTotalYear1: { low: 110, high: 350 },
    realAddressNote: "SC requires a real South Carolina physical address.",
  },
  {
    slug: "alabama",
    name: "Alabama",
    abbr: "AL",
    filingFee: 200,
    filingForm: "Certificate of Formation",
    franchiseTax: {
      amount: 100,
      cadence: "annual minimum",
      note: "Business Privilege Tax — $100 minimum, scaled by net worth.",
    },
    annualReport: { fee: 10, cadence: "annual (with Business Privilege Tax)" },
    registeredAgent: "Required. Must have an Alabama physical address.",
    paStateUrl: "https://arc-sos.state.al.us/CGI/CORPNAME.MBR/INPUT",
    highlights: [
      "Auto + aerospace manufacturing growth",
      "Low cost of living relative to coastal states",
      "$10 annual report fee",
    ],
    watchOuts: [
      "Business Privilege Tax always applies — $100 minimum",
      "Probate court filing required at county level",
    ],
    estTotalYear1: { low: 310, high: 600 },
    realAddressNote: "AL requires a real Alabama physical address.",
  },
  {
    slug: "kentucky",
    name: "Kentucky",
    abbr: "KY",
    filingFee: 40,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 15, cadence: "annual" },
    registeredAgent: "Required. Must have a Kentucky physical address.",
    paStateUrl: "https://app.sos.ky.gov/ftsearch/",
    highlights: [
      "$40 filing — among the lowest in the US",
      "$15 annual report",
      "No franchise tax for LLCs",
    ],
    watchOuts: [
      "LLET (Limited Liability Entity Tax) applies above $3M revenue",
      "Annual report due June 30",
    ],
    estTotalYear1: { low: 55, high: 250 },
    realAddressNote: "KY requires a real Kentucky physical address.",
  },
  {
    slug: "louisiana",
    name: "Louisiana",
    abbr: "LA",
    filingFee: 100,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 35, cadence: "annual" },
    registeredAgent: "Required. Must have a Louisiana physical address.",
    paStateUrl: "https://coraweb.sos.la.gov/CommercialSearch/CommercialSearch.aspx",
    highlights: [
      "Tourism + oil & gas + film tax credits",
      "No franchise tax for LLCs (corps only)",
      "Civil law system (unique in US)",
    ],
    watchOuts: [
      "Civil law parishes (not counties) — local filings differ",
      "Sales tax structure is among the most complex in the US",
    ],
    estTotalYear1: { low: 135, high: 400 },
    realAddressNote: "LA requires a real Louisiana physical address.",
  },
  {
    slug: "utah",
    name: "Utah",
    abbr: "UT",
    filingFee: 59,
    filingForm: "Certificate of Organization",
    franchiseTax: null,
    annualReport: { fee: 18, cadence: "annual" },
    registeredAgent: "Required. Must have a Utah physical address.",
    paStateUrl: "https://secure.utah.gov/bes/index.html",
    highlights: [
      "$59 filing fee (low)",
      "$18 annual report (very low)",
      "Silicon Slopes — fastest-growing tech hub outside CA",
    ],
    watchOuts: [
      "Annual renewal due each year on registration anniversary",
      "Local business licenses vary by city",
    ],
    estTotalYear1: { low: 77, high: 300 },
    realAddressNote: "UT requires a real Utah physical address.",
  },
  {
    slug: "delaware",
    name: "Delaware",
    abbr: "DE",
    filingFee: 110,
    filingForm: "Certificate of Formation",
    franchiseTax: {
      amount: 300,
      cadence: "annual flat",
      note: "Delaware LLCs pay $300/year flat franchise tax (much simpler than Delaware corp franchise tax).",
    },
    annualReport: null,
    registeredAgent: "Required. Must have a Delaware physical address — most non-DE owners use a registered-agent service.",
    paStateUrl: "https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx",
    highlights: [
      "Most popular state for incorporation in the US (1M+ entities)",
      "Court of Chancery — best business case law in the US",
      "Privacy: members not listed on public filings",
      "$300 flat franchise tax (no annual report fee on top)",
    ],
    watchOuts: [
      "Most owners don&apos;t live in DE — must hire registered agent ($100-$300/yr)",
      "If you operate in another state, you also have to register there as foreign LLC",
      "$300/yr franchise tax even with $0 revenue",
    ],
    estTotalYear1: { low: 510, high: 900 },
    realAddressNote:
      "Delaware requires a registered agent with a DE address. Our LA address is for the principal business — if you operate from CA, you&apos;ll register the DE LLC as a foreign LLC in CA (which makes our address relevant).",
  },
  {
    slug: "wyoming",
    name: "Wyoming",
    abbr: "WY",
    filingFee: 100,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 60, cadence: "annual" },
    registeredAgent: "Required. Must have a Wyoming physical address.",
    paStateUrl: "https://wyobiz.wyo.gov/Business/FilingSearch.aspx",
    highlights: [
      "Anonymous LLC: members + managers not on public record",
      "No state income tax",
      "$60/yr annual report (low)",
      "Strong asset-protection statutes",
    ],
    watchOuts: [
      "If you operate in another state, register as foreign LLC there",
      "Annual report is based on assets in WY ($60 minimum, scales up)",
      "Need a WY registered agent if you don&apos;t live there",
    ],
    estTotalYear1: { low: 260, high: 500 },
    realAddressNote:
      "WY requires a WY registered agent. Most non-WY owners pair our LA address (for foreign-LLC filing in CA) with a WY agent service.",
  },
  {
    slug: "new-mexico",
    name: "New Mexico",
    abbr: "NM",
    filingFee: 50,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: null,
    registeredAgent: "Required. Must have a New Mexico physical address.",
    paStateUrl: "https://portal.sos.state.nm.us/BFS/online/Account",
    highlights: [
      "Anonymous LLC: members not listed on public filings",
      "$50 filing fee (very low)",
      "No annual report required",
      "No franchise tax",
    ],
    watchOuts: [
      "Need a NM registered agent if you don&apos;t live there ($50-$100/yr)",
      "If you operate elsewhere, register as foreign LLC in your operating state",
      "Less established case law than DE or WY",
    ],
    estTotalYear1: { low: 100, high: 250 },
    realAddressNote:
      "NM requires a NM registered agent. Pair our LA address with a NM agent service if you&apos;re in CA.",
  },
  {
    slug: "oklahoma",
    name: "Oklahoma",
    abbr: "OK",
    filingFee: 100,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 25, cadence: "annual" },
    registeredAgent: "Required. Must have an Oklahoma physical address.",
    paStateUrl: "https://www.sos.ok.gov/corp/corpInquiryFind.aspx",
    highlights: [
      "$25 annual report (low)",
      "Energy + agriculture economy",
      "Tulsa + OKC metro tech growth",
    ],
    watchOuts: [
      "Annual certificate due each year on registration anniversary",
      "Penalty for late filing — risk of dissolution",
    ],
    estTotalYear1: { low: 125, high: 350 },
    realAddressNote: "OK requires a real Oklahoma physical address.",
  },
  {
    slug: "iowa",
    name: "Iowa",
    abbr: "IA",
    filingFee: 50,
    filingForm: "Certificate of Organization",
    franchiseTax: null,
    annualReport: { fee: 30, cadence: "every 2 years" },
    registeredAgent: "Required. Must have an Iowa physical address.",
    paStateUrl: "https://sos.iowa.gov/search/business/search.aspx",
    highlights: [
      "$50 filing — among the cheapest",
      "$30 biennial report (very low)",
      "No franchise tax",
    ],
    watchOuts: [
      "Biennial report due in odd years between Jan 1 and Apr 1",
      "Late = $50 penalty + dissolution risk",
    ],
    estTotalYear1: { low: 80, high: 250 },
    realAddressNote: "IA requires a real Iowa physical address.",
  },
  {
    slug: "kansas",
    name: "Kansas",
    abbr: "KS",
    filingFee: 165,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 50, cadence: "annual" },
    registeredAgent: "Required. Must have a Kansas physical address.",
    paStateUrl: "https://www.kansas.gov/bess/flow/main",
    highlights: [
      "Manufacturing + aerospace economy (Wichita)",
      "Lower cost of living + commercial real estate",
    ],
    watchOuts: [
      "$165 filing fee (above average)",
      "Annual report required by April 15 — late = $35 penalty",
    ],
    estTotalYear1: { low: 215, high: 500 },
    realAddressNote: "KS requires a real Kansas physical address.",
  },
  {
    slug: "arkansas",
    name: "Arkansas",
    abbr: "AR",
    filingFee: 45,
    filingForm: "Certificate of Organization",
    franchiseTax: {
      amount: 150,
      cadence: "annual",
      note: "Annual franchise tax for LLCs.",
    },
    annualReport: { fee: 0, cadence: "filed with franchise tax" },
    registeredAgent: "Required. Must have an Arkansas physical address.",
    paStateUrl: "https://www.sos.arkansas.gov/corps/search_all.php",
    highlights: [
      "$45 online filing — very low",
      "Walmart / Tyson / J.B. Hunt corporate market",
    ],
    watchOuts: [
      "$150/yr franchise tax — even with $0 revenue",
      "Due by May 1 every year",
    ],
    estTotalYear1: { low: 195, high: 400 },
    realAddressNote: "AR requires a real Arkansas physical address.",
  },
  {
    slug: "mississippi",
    name: "Mississippi",
    abbr: "MS",
    filingFee: 50,
    filingForm: "Certificate of Formation",
    franchiseTax: null,
    annualReport: { fee: 0, cadence: "annual (free if filed on time)" },
    registeredAgent: "Required. Must have a Mississippi physical address.",
    paStateUrl: "https://corp.sos.ms.gov/corp/portal/c/page/corpBusinessIdSearch/portal.aspx",
    highlights: [
      "$50 online filing",
      "Free annual report if filed on time",
      "No franchise tax for LLCs",
    ],
    watchOuts: [
      "Annual report due April 15 — $25 late fee",
      "Failure to file = administrative dissolution",
    ],
    estTotalYear1: { low: 50, high: 250 },
    realAddressNote: "MS requires a real Mississippi physical address.",
  },
  {
    slug: "nebraska",
    name: "Nebraska",
    abbr: "NE",
    filingFee: 105,
    filingForm: "Certificate of Organization",
    franchiseTax: null,
    annualReport: { fee: 13, cadence: "every 2 years" },
    registeredAgent: "Required. Must have a Nebraska physical address.",
    paStateUrl: "https://www.nebraska.gov/sos/corp/corpsearch.cgi",
    highlights: [
      "$13 biennial report — among the cheapest in the US",
      "No franchise tax",
      "Stable economy + low cost of doing business",
    ],
    watchOuts: [
      "Notice of organization must be published in newspaper for 3 weeks (~$50-$200)",
      "Biennial report due odd years by April 1",
    ],
    estTotalYear1: { low: 200, high: 400 },
    realAddressNote: "NE requires a real Nebraska physical address.",
  },
  {
    slug: "new-hampshire",
    name: "New Hampshire",
    abbr: "NH",
    filingFee: 100,
    filingForm: "Certificate of Formation",
    franchiseTax: {
      amount: 0,
      cadence: "no tax — but BPT/BET on profits",
      note: "BPT (Business Profits Tax) at 7.5% on net income above ~$100k. Most micro-LLCs aren&apos;t affected.",
    },
    annualReport: { fee: 100, cadence: "annual" },
    registeredAgent: "Required. Must have a New Hampshire physical address.",
    paStateUrl: "https://quickstart.sos.nh.gov/online/BusinessInquire/",
    highlights: [
      "No personal income tax + no sales tax",
      "Boston-area commute economy without MA cost",
      "Strong tech corridor (Manchester / Nashua)",
    ],
    watchOuts: [
      "BPT/BET tax structure can apply to high-revenue LLCs",
      "$100 annual report (above average)",
    ],
    estTotalYear1: { low: 200, high: 500 },
    realAddressNote: "NH requires a real New Hampshire physical address.",
  },
  {
    slug: "idaho",
    name: "Idaho",
    abbr: "ID",
    filingFee: 100,
    filingForm: "Certificate of Organization",
    franchiseTax: null,
    annualReport: { fee: 0, cadence: "annual (free if filed on time)" },
    registeredAgent: "Required. Must have an Idaho physical address.",
    paStateUrl: "https://sosbiz.idaho.gov/search/business",
    highlights: [
      "$100 filing fee",
      "Free annual report (if filed on time)",
      "Boise tech-corridor growth + low cost of living",
    ],
    watchOuts: [
      "Late annual report = $30 + administrative dissolution risk",
      "Anniversary-month due date — easy to miss without reminder",
    ],
    estTotalYear1: { low: 100, high: 300 },
    realAddressNote: "ID requires a real Idaho physical address.",
  },
  {
    slug: "west-virginia",
    name: "West Virginia",
    abbr: "WV",
    filingFee: 100,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 25, cadence: "annual" },
    registeredAgent: "Required. Must have a West Virginia physical address.",
    paStateUrl: "https://apps.sos.wv.gov/business/corporations/",
    highlights: [
      "$25 annual report (low)",
      "No franchise tax",
      "Recent business-friendly tax reforms",
    ],
    watchOuts: [
      "Annual report due July 1 — late = $50 penalty",
      "Severance taxes apply for natural-resource businesses",
    ],
    estTotalYear1: { low: 125, high: 300 },
    realAddressNote: "WV requires a real West Virginia physical address.",
  },
  {
    slug: "maine",
    name: "Maine",
    abbr: "ME",
    filingFee: 175,
    filingForm: "Certificate of Formation",
    franchiseTax: null,
    annualReport: { fee: 85, cadence: "annual" },
    registeredAgent: "Required. Must have a Maine physical address.",
    paStateUrl: "https://icrs.informe.org/nei-sos-icrs/ICRS",
    highlights: [
      "Boston-corridor commute economy",
      "Strong tourism + maritime industries",
    ],
    watchOuts: [
      "$175 filing + $85 annual report (above average)",
      "Annual report due June 1 — late = $50 penalty",
    ],
    estTotalYear1: { low: 260, high: 500 },
    realAddressNote: "ME requires a real Maine physical address.",
  },
  {
    slug: "rhode-island",
    name: "Rhode Island",
    abbr: "RI",
    filingFee: 150,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 50, cadence: "annual" },
    registeredAgent: "Required. Must have a Rhode Island physical address.",
    paStateUrl: "https://business.sos.ri.gov/CorpWeb/CorpSearch/CorpSearch.aspx",
    highlights: [
      "Proximity to Boston + Providence economies",
      "Strong arts + design + jewelry manufacturing legacy",
    ],
    watchOuts: [
      "$150 filing + $50 annual report (above average)",
      "Annual report due Feb 1 - May 1 each year",
    ],
    estTotalYear1: { low: 200, high: 400 },
    realAddressNote: "RI requires a real Rhode Island physical address.",
  },
  {
    slug: "vermont",
    name: "Vermont",
    abbr: "VT",
    filingFee: 125,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 35, cadence: "annual" },
    registeredAgent: "Required. Must have a Vermont physical address.",
    paStateUrl: "https://www.vtsosonline.com/online/BusinessInquire/",
    highlights: [
      "$35 annual report (low)",
      "Strong agriculture + maple + craft brewing economy",
      "Innovative B-corp legislation",
    ],
    watchOuts: [
      "Annual report due within 3 months of fiscal-year close",
      "Out-of-state owners need a VT registered agent",
    ],
    estTotalYear1: { low: 160, high: 350 },
    realAddressNote: "VT requires a real Vermont physical address.",
  },
  {
    slug: "south-dakota",
    name: "South Dakota",
    abbr: "SD",
    filingFee: 150,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 50, cadence: "annual" },
    registeredAgent: "Required. Must have a South Dakota physical address.",
    paStateUrl: "https://sosenterprise.sd.gov/BusinessServices/Business/FilingSearch.aspx",
    highlights: [
      "No state income tax",
      "Best-in-class trust + asset-protection statutes",
      "Sioux Falls financial-services hub",
    ],
    watchOuts: [
      "$50/yr annual report",
      "Trusts in SD typically need separate trustee setup",
    ],
    estTotalYear1: { low: 200, high: 400 },
    realAddressNote: "SD requires a real South Dakota physical address.",
  },
  {
    slug: "north-dakota",
    name: "North Dakota",
    abbr: "ND",
    filingFee: 135,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 50, cadence: "annual" },
    registeredAgent: "Required. Must have a North Dakota physical address.",
    paStateUrl: "https://firststop.sos.nd.gov/search",
    highlights: [
      "Strong energy + agriculture economy",
      "$50/yr annual report",
    ],
    watchOuts: [
      "Annual report due Nov 15 — late = $50 penalty",
    ],
    estTotalYear1: { low: 185, high: 400 },
    realAddressNote: "ND requires a real North Dakota physical address.",
  },
  {
    slug: "montana",
    name: "Montana",
    abbr: "MT",
    filingFee: 35,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 20, cadence: "annual" },
    registeredAgent: "Required. Must have a Montana physical address.",
    paStateUrl: "https://biz.sosmt.gov/",
    highlights: [
      "$35 filing fee — among the lowest in the US",
      "$20 annual report — very low",
      "No state sales tax",
    ],
    watchOuts: [
      "Annual report due April 15 — late = $15 penalty",
      "Strict zoning if you operate in tourism-heavy areas",
    ],
    estTotalYear1: { low: 55, high: 250 },
    realAddressNote: "MT requires a real Montana physical address.",
  },
  {
    slug: "alaska",
    name: "Alaska",
    abbr: "AK",
    filingFee: 250,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 100, cadence: "every 2 years" },
    registeredAgent: "Required. Must have an Alaska physical address.",
    paStateUrl: "https://www.commerce.alaska.gov/cbp/main/search/entities",
    highlights: [
      "No state sales tax + no income tax",
      "Strong fishing + tourism + energy industries",
    ],
    watchOuts: [
      "$250 filing fee (above average)",
      "Biennial report + business license required",
      "$50 business license fee on top of filing",
    ],
    estTotalYear1: { low: 350, high: 700 },
    realAddressNote: "AK requires a real Alaska physical address.",
  },
  {
    slug: "hawaii",
    name: "Hawaii",
    abbr: "HI",
    filingFee: 50,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 15, cadence: "annual" },
    registeredAgent: "Required. Must have a Hawaii physical address.",
    paStateUrl: "https://hbe.ehawaii.gov/documents/search.html",
    highlights: [
      "$50 filing + $15 annual — low cost of formation",
      "Strong tourism + Pacific-rim trade economy",
    ],
    watchOuts: [
      "General Excise Tax (GET) ~4.5% applies to all gross income",
      "Annual report due in registration anniversary quarter",
    ],
    estTotalYear1: { low: 65, high: 300 },
    realAddressNote: "HI requires a real Hawaii physical address.",
  },
  {
    slug: "washington-dc",
    name: "Washington DC",
    abbr: "DC",
    filingFee: 220,
    filingForm: "Articles of Organization",
    franchiseTax: null,
    annualReport: { fee: 300, cadence: "every 2 years" },
    registeredAgent: "Required. Must have a DC physical address.",
    paStateUrl: "https://corponline.dcra.dc.gov/Account.aspx/LogOn",
    highlights: [
      "Federal-contracting market access",
      "Strong nonprofit + advocacy + lobbying ecosystem",
    ],
    watchOuts: [
      "$220 filing fee + $300 biennial report (high)",
      "DC Unincorporated Business Tax (UBT) at 8.25% on income",
    ],
    estTotalYear1: { low: 520, high: 900 },
    realAddressNote: "DC requires a real DC physical address.",
  },
];

export const STATE_LLC_BY_SLUG: Record<string, StateLLC> = Object.fromEntries(
  STATE_LLC_PAGES.map((s) => [s.slug, s]),
);

export function getStateLLC(slug: string): StateLLC | null {
  return STATE_LLC_BY_SLUG[slug] ?? null;
}

export function getAllStateSlugs(): string[] {
  return STATE_LLC_PAGES.map((s) => s.slug);
}
