import type { Metadata, Viewport } from "next";
import { Inter, Baloo_2, Pacifico } from "next/font/google";
import "./globals.css";
import { InteractiveCursor } from "@/components/InteractiveCursor";
import { ScrollProgress } from "@/components/ScrollProgress";
import { Ripple } from "@/components/Ripple";
import { LocaleProvider } from "@/lib/i18n/LocaleProvider";
import { LOCALE_META } from "@/lib/i18n/dictionary";
import { getServerLocale } from "@/app/actions/locale";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

// Brand display family — used by `var(--font-baloo)` on marketing
// headlines + iPad-OS admin titles. Was previously referenced in
// `fontFamily: "var(--font-baloo), 'Baloo 2', sans-serif"` strings but
// never actually loaded — those headlines fell through to the system
// fallback. Loading here makes them render as designed.
const baloo = Baloo_2({
  variable: "--font-baloo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

// Brand script accent — used for the small italic-script taglines next
// to admin H2s ("set the vibe", "spot the bad apples", etc).
const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const viewport: Viewport = {
  // Cream `#F7E6C2` matches the live hero brand across the public site so
  // Safari's status bar + Chrome Android's chrome bar tint to the brand
  // instead of the old dark placeholder.
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#F7E6C2" },
    { media: "(prefers-color-scheme: dark)", color: "#2D100F" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 5, // 5× is WCAG-safe + lets users pinch-zoom for accessibility
};

export const metadata: Metadata = {
  title: {
    default: "NOHO Mailbox — Private Mailbox Rental in North Hollywood, CA",
    // Geo-anchored template — every inner page picks up "North Hollywood"
    // in the SERP title, which is the dominant local-intent keyword for
    // every service we sell (mailbox, notary, courier, LLC).
    template: "%s · NOHO Mailbox · North Hollywood, CA",
  },
  description:
    "Private mailbox rental in North Hollywood, CA with a real street address, digital mail scanning, package handling, same-day delivery, walk-in notary, and full business formation. Plans from $50.",
  keywords: [
    "private mailbox North Hollywood",
    "mailbox rental NoHo",
    "virtual mailbox Los Angeles",
    "mail scanning North Hollywood",
    "real street address NoHo",
    "USPS Form 1583 North Hollywood",
    "PO Box alternative North Hollywood",
    "mail forwarding Los Angeles",
    "notary North Hollywood",
    "walk-in notary NoHo",
    "business formation North Hollywood",
    "LLC formation Los Angeles",
    "package receiving service NoHo",
    "same-day delivery San Fernando Valley",
    "shipping supplies North Hollywood",
    "small business address NoHo",
  ],
  authors: [{ name: "NOHO Mailbox" }],
  creator: "NOHO Mailbox",
  publisher: "NOHO Mailbox",
  category: "Mailbox Rental & Business Services",
  icons: { icon: "/icon.svg", apple: "/icon.svg" },
  manifest: "/manifest.json",
  metadataBase: new URL("https://nohomailbox.org"),
  alternates: {
    canonical: "https://nohomailbox.org",
    types: {
      "application/rss+xml": [
        {
          url: "https://nohomailbox.org/feed.xml",
          title: "NOHO Mailbox — Blog RSS feed",
        },
      ],
    },
  },
  openGraph: {
    siteName: "NOHO Mailbox",
    type: "website",
    locale: "en_US",
    url: "https://nohomailbox.org",
    images: [
      {
        url: "/og-image.svg",
        width: 1200,
        height: 630,
        alt: "NOHO Mailbox — Private Mailbox Rental in North Hollywood, CA",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@nohomailbox",
    creator: "@nohomailbox",
    title: "NOHO Mailbox — Private Mailbox Rental in North Hollywood, CA",
    description:
      "Real LA street address from $50. Mail scanning, same-day $5 delivery, walk-in notary, $2k LLC + brand bundle. Open Mon-Sat at 5062 Lankershim.",
    // Dynamic 1200×630 PNG generated by app/(marketing)/opengraph-image.tsx
    // — already crawler-readable from the route, so Twitter picks it up.
    images: [{ url: "/og-image.svg", alt: "NOHO Mailbox — North Hollywood mailbox + same-day delivery" }],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  verification: {
    // Add real verification codes here when available
    // google: "your-google-site-verification",
  },
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // iter-110: pick locale from cookie / Accept-Language so SSR + client
  // see the same dir/lang attrs and translated strings on first paint.
  const locale = await getServerLocale();
  const dir = LOCALE_META[locale].dir;
  return (
    <html lang={locale} dir={dir} className={`${inter.variable} ${baloo.variable} ${pacifico.variable}`}>
      <body className="min-h-screen flex flex-col font-[family-name:var(--font-inter)] antialiased">
        <LocaleProvider initial={locale}>
          <ScrollProgress />
          {children}
          <InteractiveCursor />
          <Ripple />
        </LocaleProvider>
      </body>
    </html>
  );
}
